// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Message.proto</summary>
public static partial class MessageReflection {

  #region Descriptor
  /// <summary>File descriptor for Message.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1NZXNzYWdlLnByb3RvIkUKCFJvb21Vc2VyEgwKBG5hbWUYASABKAkSDAoE",
          "c2VhdBgCIAEoBRIOCgZhdmF0YXIYAyABKAkSDQoFc2NvcmUYBCABKAUiSwoI",
          "Um9vbUluZm8SDAoEbmFtZRgBIAEoCRIOCgZjb3VudHMYAiABKAUSDgoGYXZh",
          "dGFyGAMgASgJEhEKCWdhbWVCZWdpbhgEIAEoCCLgBAoIUHJvdG9jb2wSCwoD",
          "a2V5GAEgASgJEiQKBHR5cGUYAiABKA4yFi5Qcm90b2NvbC5Qcm90b2NvbFR5",
          "cGUSEQoJYnJvYWRjYXN0GAMgASgIEgwKBG5hbWUYBCABKAkSDgoGYXZhdGFy",
          "GAUgASgJEgwKBHNlYXQYBiABKAUSEAoIcm9vbV9rZXkYByABKAkSEQoJcm9v",
          "bV9uYW1lGAggASgJEg8KB21lc3NhZ2UYCSABKAkSEwoLYmVnaW5fcG9pbnQY",
          "CiABKAESEQoJZW5kX3BvaW50GAsgASgBEhAKCHBlbl9zaXplGAwgASgFEg0K",
          "BWNvbG9yGA0gASgFEhgKBXVzZXJzGA4gAygLMgkuUm9vbVVzZXISGAoFcm9v",
          "bXMYDyADKAsyCS5Sb29tSW5mbxIMCgRjb2RlGBAgASgFEg0KBWVycm9yGBEg",
          "ASgJEgoKAmlkGBIgASgFIoUCCgxQcm90b2NvbFR5cGUSCQoFTE9HSU4QABIP",
          "CgtDUkVBVEVfUk9PTRABEg0KCUpPSU5fUk9PTRACEg4KCkxFQVZFX1JPT00Q",
          "AxIICgRDSEFUEAQSDgoKR0FNRV9CRUdJThAFEgwKCEdBTUVfRU5EEAYSCQoF",
          "UEFJTlQQBxIQCgxFTlRFUkVEX1JPT00QCBIPCgtMRUFWRURfUk9PTRAJEgsK",
          "B09GRkxJTkUQChIKCgZPTkxJTkUQCxIJCgVSRUFEWRAMEg8KC1VQREFURV9V",
          "U0VSEA0SDQoJQ09VTlRET1dOEA4SEQoNR0FNRV9GSU5JU0hFRBAPEg0KCVJP",
          "T01fTElTVBAQYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::RoomUser), global::RoomUser.Parser, new[]{ "Name", "Seat", "Avatar", "Score" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::RoomInfo), global::RoomInfo.Parser, new[]{ "Name", "Counts", "Avatar", "GameBegin" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Protocol), global::Protocol.Parser, new[]{ "Key", "Type", "Broadcast", "Name", "Avatar", "Seat", "RoomKey", "RoomName", "Message", "BeginPoint", "EndPoint", "PenSize", "Color", "Users", "Rooms", "Code", "Error", "Id" }, null, new[]{ typeof(global::Protocol.Types.ProtocolType) }, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class RoomUser : pb::IMessage<RoomUser> {
  private static readonly pb::MessageParser<RoomUser> _parser = new pb::MessageParser<RoomUser>(() => new RoomUser());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RoomUser> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoomUser() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoomUser(RoomUser other) : this() {
    name_ = other.name_;
    seat_ = other.seat_;
    avatar_ = other.avatar_;
    score_ = other.score_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoomUser Clone() {
    return new RoomUser(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "seat" field.</summary>
  public const int SeatFieldNumber = 2;
  private int seat_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Seat {
    get { return seat_; }
    set {
      seat_ = value;
    }
  }

  /// <summary>Field number for the "avatar" field.</summary>
  public const int AvatarFieldNumber = 3;
  private string avatar_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Avatar {
    get { return avatar_; }
    set {
      avatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "score" field.</summary>
  public const int ScoreFieldNumber = 4;
  private int score_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Score {
    get { return score_; }
    set {
      score_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RoomUser);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RoomUser other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Seat != other.Seat) return false;
    if (Avatar != other.Avatar) return false;
    if (Score != other.Score) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Seat != 0) hash ^= Seat.GetHashCode();
    if (Avatar.Length != 0) hash ^= Avatar.GetHashCode();
    if (Score != 0) hash ^= Score.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Seat != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Seat);
    }
    if (Avatar.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Avatar);
    }
    if (Score != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Score);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Seat != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seat);
    }
    if (Avatar.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Avatar);
    }
    if (Score != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Score);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RoomUser other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Seat != 0) {
      Seat = other.Seat;
    }
    if (other.Avatar.Length != 0) {
      Avatar = other.Avatar;
    }
    if (other.Score != 0) {
      Score = other.Score;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Seat = input.ReadInt32();
          break;
        }
        case 26: {
          Avatar = input.ReadString();
          break;
        }
        case 32: {
          Score = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class RoomInfo : pb::IMessage<RoomInfo> {
  private static readonly pb::MessageParser<RoomInfo> _parser = new pb::MessageParser<RoomInfo>(() => new RoomInfo());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<RoomInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoomInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoomInfo(RoomInfo other) : this() {
    name_ = other.name_;
    counts_ = other.counts_;
    avatar_ = other.avatar_;
    gameBegin_ = other.gameBegin_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public RoomInfo Clone() {
    return new RoomInfo(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "counts" field.</summary>
  public const int CountsFieldNumber = 2;
  private int counts_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Counts {
    get { return counts_; }
    set {
      counts_ = value;
    }
  }

  /// <summary>Field number for the "avatar" field.</summary>
  public const int AvatarFieldNumber = 3;
  private string avatar_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Avatar {
    get { return avatar_; }
    set {
      avatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "gameBegin" field.</summary>
  public const int GameBeginFieldNumber = 4;
  private bool gameBegin_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool GameBegin {
    get { return gameBegin_; }
    set {
      gameBegin_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as RoomInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(RoomInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Counts != other.Counts) return false;
    if (Avatar != other.Avatar) return false;
    if (GameBegin != other.GameBegin) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Counts != 0) hash ^= Counts.GetHashCode();
    if (Avatar.Length != 0) hash ^= Avatar.GetHashCode();
    if (GameBegin != false) hash ^= GameBegin.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Counts != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Counts);
    }
    if (Avatar.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Avatar);
    }
    if (GameBegin != false) {
      output.WriteRawTag(32);
      output.WriteBool(GameBegin);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Counts != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Counts);
    }
    if (Avatar.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Avatar);
    }
    if (GameBegin != false) {
      size += 1 + 1;
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(RoomInfo other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Counts != 0) {
      Counts = other.Counts;
    }
    if (other.Avatar.Length != 0) {
      Avatar = other.Avatar;
    }
    if (other.GameBegin != false) {
      GameBegin = other.GameBegin;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 16: {
          Counts = input.ReadInt32();
          break;
        }
        case 26: {
          Avatar = input.ReadString();
          break;
        }
        case 32: {
          GameBegin = input.ReadBool();
          break;
        }
      }
    }
  }

}

public sealed partial class Protocol : pb::IMessage<Protocol> {
  private static readonly pb::MessageParser<Protocol> _parser = new pb::MessageParser<Protocol>(() => new Protocol());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Protocol> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MessageReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Protocol() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Protocol(Protocol other) : this() {
    key_ = other.key_;
    type_ = other.type_;
    broadcast_ = other.broadcast_;
    name_ = other.name_;
    avatar_ = other.avatar_;
    seat_ = other.seat_;
    roomKey_ = other.roomKey_;
    roomName_ = other.roomName_;
    message_ = other.message_;
    beginPoint_ = other.beginPoint_;
    endPoint_ = other.endPoint_;
    penSize_ = other.penSize_;
    color_ = other.color_;
    users_ = other.users_.Clone();
    rooms_ = other.rooms_.Clone();
    code_ = other.code_;
    error_ = other.error_;
    id_ = other.id_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Protocol Clone() {
    return new Protocol(this);
  }

  /// <summary>Field number for the "key" field.</summary>
  public const int KeyFieldNumber = 1;
  private string key_ = "";
  /// <summary>
  /// 用户唯一标识
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Key {
    get { return key_; }
    set {
      key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 2;
  private global::Protocol.Types.ProtocolType type_ = 0;
  /// <summary>
  /// 哪种消息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Protocol.Types.ProtocolType Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "broadcast" field.</summary>
  public const int BroadcastFieldNumber = 3;
  private bool broadcast_;
  /// <summary>
  /// 是否是广播
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Broadcast {
    get { return broadcast_; }
    set {
      broadcast_ = value;
    }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 4;
  private string name_ = "";
  /// <summary>
  /// 用户名
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "avatar" field.</summary>
  public const int AvatarFieldNumber = 5;
  private string avatar_ = "";
  /// <summary>
  /// 头像
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Avatar {
    get { return avatar_; }
    set {
      avatar_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "seat" field.</summary>
  public const int SeatFieldNumber = 6;
  private int seat_;
  /// <summary>
  /// 座位号
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Seat {
    get { return seat_; }
    set {
      seat_ = value;
    }
  }

  /// <summary>Field number for the "room_key" field.</summary>
  public const int RoomKeyFieldNumber = 7;
  private string roomKey_ = "";
  /// <summary>
  /// 房间唯一标识
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string RoomKey {
    get { return roomKey_; }
    set {
      roomKey_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "room_name" field.</summary>
  public const int RoomNameFieldNumber = 8;
  private string roomName_ = "";
  /// <summary>
  /// 房间名称
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string RoomName {
    get { return roomName_; }
    set {
      roomName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "message" field.</summary>
  public const int MessageFieldNumber = 9;
  private string message_ = "";
  /// <summary>
  /// 聊天内容
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Message {
    get { return message_; }
    set {
      message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "begin_point" field.</summary>
  public const int BeginPointFieldNumber = 10;
  private double beginPoint_;
  /// <summary>
  /// 游戏开始后，起笔的坐标
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double BeginPoint {
    get { return beginPoint_; }
    set {
      beginPoint_ = value;
    }
  }

  /// <summary>Field number for the "end_point" field.</summary>
  public const int EndPointFieldNumber = 11;
  private double endPoint_;
  /// <summary>
  ///游戏开始后，落笔的坐标
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public double EndPoint {
    get { return endPoint_; }
    set {
      endPoint_ = value;
    }
  }

  /// <summary>Field number for the "pen_size" field.</summary>
  public const int PenSizeFieldNumber = 12;
  private int penSize_;
  /// <summary>
  /// 游戏开始后，笔的尺寸
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PenSize {
    get { return penSize_; }
    set {
      penSize_ = value;
    }
  }

  /// <summary>Field number for the "color" field.</summary>
  public const int ColorFieldNumber = 13;
  private int color_;
  /// <summary>
  /// 游戏开始后，线条的颜色
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Color {
    get { return color_; }
    set {
      color_ = value;
    }
  }

  /// <summary>Field number for the "users" field.</summary>
  public const int UsersFieldNumber = 14;
  private static readonly pb::FieldCodec<global::RoomUser> _repeated_users_codec
      = pb::FieldCodec.ForMessage(114, global::RoomUser.Parser);
  private readonly pbc::RepeatedField<global::RoomUser> users_ = new pbc::RepeatedField<global::RoomUser>();
  /// <summary>
  /// 房间里用户信息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::RoomUser> Users {
    get { return users_; }
  }

  /// <summary>Field number for the "rooms" field.</summary>
  public const int RoomsFieldNumber = 15;
  private static readonly pb::FieldCodec<global::RoomInfo> _repeated_rooms_codec
      = pb::FieldCodec.ForMessage(122, global::RoomInfo.Parser);
  private readonly pbc::RepeatedField<global::RoomInfo> rooms_ = new pbc::RepeatedField<global::RoomInfo>();
  /// <summary>
  /// 大厅里房间信息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::RoomInfo> Rooms {
    get { return rooms_; }
  }

  /// <summary>Field number for the "code" field.</summary>
  public const int CodeFieldNumber = 16;
  private int code_;
  /// <summary>
  /// 服务端返回信息
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Code {
    get { return code_; }
    set {
      code_ = value;
    }
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 17;
  private string error_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Error {
    get { return error_; }
    set {
      error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 18;
  private int id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Protocol);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Protocol other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Key != other.Key) return false;
    if (Type != other.Type) return false;
    if (Broadcast != other.Broadcast) return false;
    if (Name != other.Name) return false;
    if (Avatar != other.Avatar) return false;
    if (Seat != other.Seat) return false;
    if (RoomKey != other.RoomKey) return false;
    if (RoomName != other.RoomName) return false;
    if (Message != other.Message) return false;
    if (BeginPoint != other.BeginPoint) return false;
    if (EndPoint != other.EndPoint) return false;
    if (PenSize != other.PenSize) return false;
    if (Color != other.Color) return false;
    if(!users_.Equals(other.users_)) return false;
    if(!rooms_.Equals(other.rooms_)) return false;
    if (Code != other.Code) return false;
    if (Error != other.Error) return false;
    if (Id != other.Id) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Key.Length != 0) hash ^= Key.GetHashCode();
    if (Type != 0) hash ^= Type.GetHashCode();
    if (Broadcast != false) hash ^= Broadcast.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Avatar.Length != 0) hash ^= Avatar.GetHashCode();
    if (Seat != 0) hash ^= Seat.GetHashCode();
    if (RoomKey.Length != 0) hash ^= RoomKey.GetHashCode();
    if (RoomName.Length != 0) hash ^= RoomName.GetHashCode();
    if (Message.Length != 0) hash ^= Message.GetHashCode();
    if (BeginPoint != 0D) hash ^= BeginPoint.GetHashCode();
    if (EndPoint != 0D) hash ^= EndPoint.GetHashCode();
    if (PenSize != 0) hash ^= PenSize.GetHashCode();
    if (Color != 0) hash ^= Color.GetHashCode();
    hash ^= users_.GetHashCode();
    hash ^= rooms_.GetHashCode();
    if (Code != 0) hash ^= Code.GetHashCode();
    if (Error.Length != 0) hash ^= Error.GetHashCode();
    if (Id != 0) hash ^= Id.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Key.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Key);
    }
    if (Type != 0) {
      output.WriteRawTag(16);
      output.WriteEnum((int) Type);
    }
    if (Broadcast != false) {
      output.WriteRawTag(24);
      output.WriteBool(Broadcast);
    }
    if (Name.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Name);
    }
    if (Avatar.Length != 0) {
      output.WriteRawTag(42);
      output.WriteString(Avatar);
    }
    if (Seat != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Seat);
    }
    if (RoomKey.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(RoomKey);
    }
    if (RoomName.Length != 0) {
      output.WriteRawTag(66);
      output.WriteString(RoomName);
    }
    if (Message.Length != 0) {
      output.WriteRawTag(74);
      output.WriteString(Message);
    }
    if (BeginPoint != 0D) {
      output.WriteRawTag(81);
      output.WriteDouble(BeginPoint);
    }
    if (EndPoint != 0D) {
      output.WriteRawTag(89);
      output.WriteDouble(EndPoint);
    }
    if (PenSize != 0) {
      output.WriteRawTag(96);
      output.WriteInt32(PenSize);
    }
    if (Color != 0) {
      output.WriteRawTag(104);
      output.WriteInt32(Color);
    }
    users_.WriteTo(output, _repeated_users_codec);
    rooms_.WriteTo(output, _repeated_rooms_codec);
    if (Code != 0) {
      output.WriteRawTag(128, 1);
      output.WriteInt32(Code);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(138, 1);
      output.WriteString(Error);
    }
    if (Id != 0) {
      output.WriteRawTag(144, 1);
      output.WriteInt32(Id);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Key.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
    }
    if (Type != 0) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Broadcast != false) {
      size += 1 + 1;
    }
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Avatar.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Avatar);
    }
    if (Seat != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seat);
    }
    if (RoomKey.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomKey);
    }
    if (RoomName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(RoomName);
    }
    if (Message.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
    }
    if (BeginPoint != 0D) {
      size += 1 + 8;
    }
    if (EndPoint != 0D) {
      size += 1 + 8;
    }
    if (PenSize != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PenSize);
    }
    if (Color != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Color);
    }
    size += users_.CalculateSize(_repeated_users_codec);
    size += rooms_.CalculateSize(_repeated_rooms_codec);
    if (Code != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Code);
    }
    if (Error.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(Error);
    }
    if (Id != 0) {
      size += 2 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Protocol other) {
    if (other == null) {
      return;
    }
    if (other.Key.Length != 0) {
      Key = other.Key;
    }
    if (other.Type != 0) {
      Type = other.Type;
    }
    if (other.Broadcast != false) {
      Broadcast = other.Broadcast;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Avatar.Length != 0) {
      Avatar = other.Avatar;
    }
    if (other.Seat != 0) {
      Seat = other.Seat;
    }
    if (other.RoomKey.Length != 0) {
      RoomKey = other.RoomKey;
    }
    if (other.RoomName.Length != 0) {
      RoomName = other.RoomName;
    }
    if (other.Message.Length != 0) {
      Message = other.Message;
    }
    if (other.BeginPoint != 0D) {
      BeginPoint = other.BeginPoint;
    }
    if (other.EndPoint != 0D) {
      EndPoint = other.EndPoint;
    }
    if (other.PenSize != 0) {
      PenSize = other.PenSize;
    }
    if (other.Color != 0) {
      Color = other.Color;
    }
    users_.Add(other.users_);
    rooms_.Add(other.rooms_);
    if (other.Code != 0) {
      Code = other.Code;
    }
    if (other.Error.Length != 0) {
      Error = other.Error;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          Key = input.ReadString();
          break;
        }
        case 16: {
          type_ = (global::Protocol.Types.ProtocolType) input.ReadEnum();
          break;
        }
        case 24: {
          Broadcast = input.ReadBool();
          break;
        }
        case 34: {
          Name = input.ReadString();
          break;
        }
        case 42: {
          Avatar = input.ReadString();
          break;
        }
        case 48: {
          Seat = input.ReadInt32();
          break;
        }
        case 58: {
          RoomKey = input.ReadString();
          break;
        }
        case 66: {
          RoomName = input.ReadString();
          break;
        }
        case 74: {
          Message = input.ReadString();
          break;
        }
        case 81: {
          BeginPoint = input.ReadDouble();
          break;
        }
        case 89: {
          EndPoint = input.ReadDouble();
          break;
        }
        case 96: {
          PenSize = input.ReadInt32();
          break;
        }
        case 104: {
          Color = input.ReadInt32();
          break;
        }
        case 114: {
          users_.AddEntriesFrom(input, _repeated_users_codec);
          break;
        }
        case 122: {
          rooms_.AddEntriesFrom(input, _repeated_rooms_codec);
          break;
        }
        case 128: {
          Code = input.ReadInt32();
          break;
        }
        case 138: {
          Error = input.ReadString();
          break;
        }
        case 144: {
          Id = input.ReadInt32();
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the Protocol message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum ProtocolType {
      [pbr::OriginalName("LOGIN")] Login = 0,
      [pbr::OriginalName("CREATE_ROOM")] CreateRoom = 1,
      [pbr::OriginalName("JOIN_ROOM")] JoinRoom = 2,
      [pbr::OriginalName("LEAVE_ROOM")] LeaveRoom = 3,
      [pbr::OriginalName("CHAT")] Chat = 4,
      [pbr::OriginalName("GAME_BEGIN")] GameBegin = 5,
      [pbr::OriginalName("GAME_END")] GameEnd = 6,
      [pbr::OriginalName("PAINT")] Paint = 7,
      [pbr::OriginalName("ENTERED_ROOM")] EnteredRoom = 8,
      [pbr::OriginalName("LEAVED_ROOM")] LeavedRoom = 9,
      [pbr::OriginalName("OFFLINE")] Offline = 10,
      [pbr::OriginalName("ONLINE")] Online = 11,
      [pbr::OriginalName("READY")] Ready = 12,
      /// <summary>
      /// 更新用户分数
      /// </summary>
      [pbr::OriginalName("UPDATE_USER")] UpdateUser = 13,
      /// <summary>
      /// 游戏倒计时
      /// </summary>
      [pbr::OriginalName("COUNTDOWN")] Countdown = 14,
      /// <summary>
      /// 一轮游戏结束
      /// </summary>
      [pbr::OriginalName("GAME_FINISHED")] GameFinished = 15,
      [pbr::OriginalName("ROOM_LIST")] RoomList = 16,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
